sudo: required

language: php

services:
  - docker

before_install:
 - docker-compose pull
 - docker-compose build
 - docker-compose start
 - docker ps
 - travis_retry composer self-update
 - composer install

script: phpunit --bootstrap vendor/autoload.php