version: "3.2"
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3308:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - storage:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d/:ro
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9001:9000
    volumes:
      - ./src/:/var/www/src
      - ./vendor/:/var/www/vendor
      - ./application.php:/var/www/application.php
      - ./app-config-local-docker.php:/var/www/app-config.php
volumes:
  storage:
